version: "3"

tasks:
  default:
    cmds:
      - task --list-all
  dev:
    cmds:
      - DEV=1 air
    silent: true
  build:
    cmds:
      - go build -o bin/sp.exe cmd/main.go
    silent: true
  deploy:
    deps:
      - build
    cmds:
      - systemctl stop startpage
      - cp bin/sp.exe /opt/startpage/bin/sp.exe
      - systemctl restart startpage
    silent: true
