version: "3"

includes:
  deploy: assets/deploy.Taskfile.yml

tasks:
  default:
    cmds:
      - task --list-all

  deploy:
    deps:
      - build
    cmds:
      - task: deploy:config
      - task: deploy:service
    silent: true
